name: Pylint

on: [push, pull_request]

jobs:
  formatting-and-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pylint
          pip install .

      - name: Run Pylint on mhkit/loads/
        run: |
          pylint mhkit/loads/

      - name: Run Pylint on mhkit/power/
        run: |
          pylint mhkit/power/

      - name: Run Pylint on mhkit/utils/
        run: |
          pylint mhkit/utils/

      - name: Run Pylint on mhkit/acoustics/
        run: |
          pylint mhkit/acoustics/

      - name: Run Pylint on mhkit/tidal
        run: |
          pylint mhkit/tidal/
